<h2 id="omne">O mě</h2>

<p class="text"><img src="images/foto.png" class="foto" alt="Foto">
Jsem Tomáš Horák a pocházím z Mostu. Na Vysoké škole Báňské - Technické univerzitě Ostrava jsem 
získal bakalářský titul v oboru Zpracování a zneškodňování odpadů. Již v době studia jsem se 
poprvé setkal s tvorbou statických webových stránek v HTML a CSS. Mé výtvory z té doby ale vypadaly
hrůzostrašně.</p>

<p class="text">Později jsem se jako samouk začal více zajímat o tvorbu dynamických webových stránek
a začal jsem ze zdrojů na internetu a z knih studovat. Dnes mám středně pokročilé znalosti HTML 5, CSS 3, 
objektově orientovaného programování v PHP, programování s využitím frameworku Nette a práce s databází 
MySQL. Ve svém samostudiu stále pokračuji a vedle rozvíjení stávajících dovedností, se začínám učit 
JavaScript.</p>

<p class="text">Ve svém volném čase se zajímám o novinky z oblasti IT. Občas rád sednu na kolo,
skočím do bazénu nebo se věnuji fotografování. Jsem také velkým fanouškem hokeje a rockové a 
metalové muziky.</p>
<div class="clear"></div>